#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL
#
# @type Quadrotor Wide
#
# @maintainer Julian Oes <julian@oes.ch>
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MC_ROLL_P 4
param set-default MC_ROLLRATE_P 0.23
param set-default MC_ROLLRATE_I 0.3
param set-default MC_ROLLRATE_D 0.0055
param set-default MC_ROLLRATE_FF 0

param set-default MC_PITCH_P 3.68
param set-default MC_PITCHRATE_P 0.26
param set-default MC_PITCHRATE_I 0.356
param set-default MC_PITCHRATE_D 0.0053
param set-default MC_PITCHRATE_FF 0

param set-default MC_YAW_P 5.35
param set-default MC_YAWRATE_P 0.18
param set-default MC_YAWRATE_I 0.18
param set-default MC_YAWRATE_D 0.01
param set-default MC_YAWRATE_FF 0

param set-default MPC_Z_VEL_P_ACC 4.5
param set-default MPC_Z_VEL_I_ACC 2.0
param set-default MPC_Z_VEL_D_ACC 0
param set-default MPC_Z_P 1.35
param set-default MPC_XY_VEL_P_ACC 2.25
param set-default MPC_XY_VEL_I_ACC 1.6
param set-default MPC_XY_VEL_D_ACC 0.4
param set-default MPC_XY_P 1.35

set MIXER quad_w
