#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL
#
# @type Quadrotor Wide
#
# @maintainer Julian Oes <julian@oes.ch>
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MC_ROLL_P 6.5
param set-default MC_ROLLRATE_P 0.146
param set-default MC_ROLLRATE_I 0.198
param set-default MC_ROLLRATE_D 0.0035
param set-default MC_ROLLRATE_FF 0

param set-default MC_PITCH_P 3.57
param set-default MC_PITCHRATE_P 0.267
param set-default MC_PITCHRATE_I 0.368
param set-default MC_PITCHRATE_D 0.0057
param set-default MC_PITCHRATE_FF 0

param set-default MC_YAW_P 5.09
param set-default MC_YAWRATE_P 0.19
param set-default MC_YAWRATE_I 0.18
param set-default MC_YAWRATE_D 0.0
param set-default MC_YAWRATE_FF 0

param set-default MPC_Z_VEL_P_ACC 5.5
param set-default MPC_Z_VEL_I_ACC 0.9
param set-default MPC_Z_VEL_D_ACC 0.4
param set-default MPC_Z_P 0.8
param set-default MPC_XY_VEL_P_ACC 2
param set-default MPC_XY_VEL_I_ACC 0.8
param set-default MPC_XY_VEL_D_ACC 0.4
param set-default MPC_XY_P 1.2

set MIXER quad_w
