#!/bin/sh
#
# @name Standard VTOL
#
# @type Standard VTOL
#

. ${R}etc/init.d/rc.vtol_defaults

# TODO: Enable motor failure detection when the
# VTOL no longer reports 0A for all ESCs in SITL
param set-default FD_ACT_EN 0
param set-default FD_ACT_MOT_TOUT 500

param set-default CA_AIRFRAME 2

# Physical matrix-0 motor model for MC hover INDI and Transition tests:
#   v = (B*U)*u_norm, with moment in N m and force in N.
# Rotor positions are the Classic SDF locations converted from FLU to FRD
# and expressed relative to the complete-model center of mass. With
# THR_MDL_FAC=1, normalized motor thrust is the physical thrust fraction.
# Matrix 1 keeps the legacy fixed control-surface coefficients used by the
# fixed-wing controller; the SDF aerodynamic effect varies with airspeed.
# MC INDI reads matrix 0 only.
param set-default THR_MDL_FAC 1
param set-default MPC_MASS 5.0700
param set-default MC_J_X 0.480461
param set-default MC_J_Y 0.345324
param set-default MC_J_Z 0.816889
param set-default MPC_THR_HOVER 0.2762
param set-default CA_FORCE_CUTOFF 3
param set-default CA_TORQ_CUTOFF 8

param set-default CA_ROTOR_COUNT 5
param set-default CA_ROTOR0_PX 0.350217
param set-default CA_ROTOR0_PY 0.350000
param set-default CA_ROTOR0_PZ -0.069724
param set-default CA_ROTOR0_CT 45
param set-default CA_ROTOR0_KM 0.06
param set-default CA_ROTOR1_PX -0.349783
param set-default CA_ROTOR1_PY -0.350000
param set-default CA_ROTOR1_PZ -0.069724
param set-default CA_ROTOR1_CT 45
param set-default CA_ROTOR1_KM 0.06
param set-default CA_ROTOR2_PX 0.350217
param set-default CA_ROTOR2_PY -0.350000
param set-default CA_ROTOR2_PZ -0.069724
param set-default CA_ROTOR2_CT 45
param set-default CA_ROTOR2_KM -0.06
param set-default CA_ROTOR3_PX -0.349783
param set-default CA_ROTOR3_PY 0.350000
param set-default CA_ROTOR3_PZ -0.069724
param set-default CA_ROTOR3_CT 45
param set-default CA_ROTOR3_KM -0.06
param set-default CA_ROTOR4_AX 1
param set-default CA_ROTOR4_AY 0
param set-default CA_ROTOR4_AZ 0
param set-default CA_ROTOR4_PX -0.219783
param set-default CA_ROTOR4_PY 0
param set-default CA_ROTOR4_PZ 0.000276
param set-default CA_ROTOR4_CT 100
# CA2 deliberately disables propeller torque for non-upward rotors.
param set-default CA_ROTOR4_KM 0

param set-default CA_SV_CS_COUNT 3
param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS2_TYPE 3
param set-default CA_SV_CS2_TRQ_P 1
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 201
param set-default PWM_MAIN_FUNC7 202
param set-default PWM_MAIN_FUNC8 203

param set-default FW_AIRSPD_MAX 25
param set-default FW_THR_ASPD_MAX 0.4
param set-default NPFG_PERIOD 12
param set-default FW_PR_FF 0.2
param set-default FW_PR_P 0.9
param set-default FW_PSP_OFF 2
param set-default FW_P_LIM_MIN -15
param set-default FW_RR_FF 0.1
param set-default FW_RR_P 0.3
param set-default FW_THR_TRIM 0.25
param set-default FW_THR_MAX 0.6
param set-default FW_THR_MIN 0.05
param set-default FW_T_CLMB_MAX 8
param set-default FW_T_SINK_MAX 2.7
param set-default FW_T_SINK_MIN 2.2

param set-default MC_AIRMODE 1
param set-default MC_ROLL_P 4
param set-default MC_ROLLRATE_P 0.3
param set-default MC_YAW_P 1.6
param set-default MC_YAWRATE_P 0.3


param set-default MIS_TAKEOFF_ALT 10

param set-default NAV_ACC_RAD 5

param set-default VT_FWD_THRUST_EN 4
param set-default VT_FWD_THRUST_SC 1
param set-default VT_F_TRANS_THR 0.75
param set-default VT_TYPE 2
