#!/bin/sh
#
# @name SHW09_vtol
#
# @type VTOL Ducted Fan
#

. ${R}etc/init.d/rc.vtol_defaults

param set-default MAV_TYPE 19 # For MAVLink
param set-default EKF2_FUSE_BETA 0 # side slip fusion is currently not supported for tailsitters
param set-default CBRK_AIRSPD_CHK 162128

param set-default VT_ELEV_MC_LOCK 1
param set-default VT_TS_DF_CTRL 1

# att at MC mode
param set-default MC_ROLL_P 6
param set-default MC_PITCH_P 6
param set-default MC_YAW_P 0.5

# rates at MC mode, but we also use the FW rates controller for it.
param set-default MC_ROLLRATE_P 0.45
param set-default MC_ROLLRATE_I 0.3
param set-default MC_ROLLRATE_D 0.0
param set-default MC_ROLLRATE_FF 0

param set-default MC_PITCHRATE_P 0.45
param set-default MC_PITCHRATE_I 0.3
param set-default MC_PITCHRATE_D 0.0
param set-default MC_PITCHRATE_FF 0

param set-default MC_YAWRATE_P 0.4
param set-default MC_YAWRATE_I 0.3
param set-default MC_YAWRATE_D 0
param set-default MC_YAWRATE_FF 0

param set-default USER_INDI_R_P 12.0
param set-default USER_INDI_P_P 12.0
param set-default USER_INDI_Y_P 10.0

param set-default MPC_THR_HOVER 0.5
param set-default MIS_TAKEOFF_ALT 2.5
param set-default RTL_RETURN_ALT 2.5
param set-default RTL_DESCEND_ALT 2.5

param set-default USER_CS_CUTOFF 8
param set-default IMU_DGYRO_CUTOFF 10
param set-default USER_PID_CA 0

# Single-EKF (for replay)
param set-default EKF2_MULTI_IMU 0
param set-default SENS_IMU_MODE 1

# att for FW mode.
param set-default FW_ARSP_MODE 1
param set-default FW_PSP_OFF 2

param set-default FW_ARSP_SCALE_EN 0


# FW performance
param set-default FW_AIRSPD_TRIM 16
param set-default FW_THR_CRUISE 0.35


param set-default MC_AIRMODE 1

param set-default VT_ARSP_TRANS 10
param set-default VT_B_TRANS_DUR 3
param set-default VT_F_TRANS_DUR 3
param set-default VT_TYPE 0

param set-default WV_EN 0

param set-default SDLOG_PROFILE 17
param set-default SDLOG_MODE 0

set MAV_TYPE 19
set PWM_OUT 1

set MIXER SHW09_vtol
