#!/bin/sh
#
# @name Esky (Big) Lama v4
#
# @type Coaxial Helicopter
# @class Copter
#
# @output MAIN1 Left swashplate servomotor, pitch axis
# @output MAIN2 Right swashplate servomotor, roll axis
# @output MAIN3 Upper rotor (CCW)
# @output MAIN4 Lower rotor (CW)
#
# @maintainer Emmanuel Roussel
#
# @board px4_fmu-v2 exclude
# @board intel_aerofc-v1 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then

        param set MC_ROLL_P 6
	param set MC_ROLLRATE_P 0.45
	param set MC_ROLLRATE_I 0.3
	param set MC_ROLLRATE_D 0.0
	param set MC_ROLLRATE_FF 0

	param set MC_PITCH_P 6
	param set MC_PITCHRATE_P 0.45
	param set MC_PITCHRATE_I 0.3
	param set MC_PITCHRATE_D 0.0
	param set MC_PITCHRATE_FF 0

	param set MC_YAW_P 5
	param set MC_YAWRATE_P 0.3
	param set MC_YAWRATE_I 0.1
	param set MC_YAWRATE_D 0
	param set MC_YAWRATE_FF 0

	param set MC_ACRO_EXPO_Y 0
	param set MC_ACRO_EXPO 0
	param set MC_ACRO_SUPEXPO 0
	param set MC_ACRO_SUPEXPOY 0
	param set MC_ACRO_R_MAX 90.0
	param set MC_ACRO_P_MAX 90.0
	param set MC_ACRO_Y_MAX 90.0

	param set MC_INDI_ROLL_P 12
	param set MC_INDI_PITCH_P 12
	param set MC_INDI_YAW_P 10

	param set MPC_THR_HOVER 0.5
	param set RTL_RETURN_ALT 2.5
	param set RTL_DESCEND_ALT 2.5
	param set SDLOG_PROFILE  1
	param set SDLOG_MODE  0

	param set CS1_CUTOFF  10
	param set DOMEGA_CUTOFF  10
	param set DOMEGA_D_CUTOFF  10
	param set OMEGA_CUTOFF  10
	param set IMU_DGYRO_CUTOFF  10
	# param set USE_CA 1
	param set SAMPLE_FREQ 250
	param set CYC_T 4000

	param set MC_PWM_HOVER 1500

fi


set MAV_TYPE 3

set MIXER_FILE etc/mixers-sitl/sductedfan_sitl.main.mix
set MIXER custom




