#!/bin/sh
#
# @name ductedfan4
#
# @type Ducted Fan
# @class Copter
#
# @output MAIN1 Upper rotor (CCW)
# @output MAIN2 servomotor, roll axis
# @output MAIN3 servomotor, pitch axis
# @output MAIN4 servomotor, roll axis
# @output MAIN5 servomotor, pitch axis
#
# @maintainer Emmanuel Roussel
#
# @board px4_fmu-v2 exclude
# @board intel_aerofc-v1 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.mc_defaults


param set-default MC_ROLL_P 6
param set-default MC_ROLLRATE_P 0.45
param set-default MC_ROLLRATE_I 0.3
param set-default MC_ROLLRATE_D 0.0
param set-default MC_ROLLRATE_FF 0

param set-default MC_PITCH_P 6
param set-default MC_PITCHRATE_P 0.45
param set-default MC_PITCHRATE_I 0.3
param set-default MC_PITCHRATE_D 0.0
param set-default MC_PITCHRATE_FF 0

param set-default MC_YAW_P 3
param set-default MC_YAWRATE_P 0.3
param set-default MC_YAWRATE_I 0.3
param set-default MC_YAWRATE_D 0
param set-default MC_YAWRATE_FF 0
param set-default MC_YAW_WEIGHT 1

param set-default USER_INDI_R_P 12.0
param set-default USER_INDI_P_P 12.0
param set-default USER_INDI_Y_P 10.0

param set-default MPC_THR_HOVER 0.5
param set-default RTL_RETURN_ALT 2.5
param set-default RTL_DESCEND_ALT 2.5
param set-default SDLOG_PROFILE  27
param set-default SDLOG_MODE  0

param set-default USER_CS_CUTOFF  20
param set-default IMU_GYRO_CUTOFF  80
param set-default USER_PID_CA 0

param set-default IMU_GYRO_RATEMAX  0
# param set-default IMU_INTEG_RATE  250

param set-default EKF2_ACC_B_NOISE  0.001
param set-default EKF2_ACC_NOISE  0.1
param set-default EKF2_GYR_B_NOISE  0.0005
param set-default EKF2_GYR_NOISE  0.001
param set-default EKF2_MAG_NOISE  0.01
param set-default EKF2_BARO_NOISE  1.0
param set-default EKF2_GPS_V_NOISE  0.2

set MAV_TYPE 3
set PWM_OUT 1

set MIXER ductedfan4
