#!/bin/sh
#
# @name Fly Ant
#
# @type Ducted Fan
#
# @maintainer meng chaoheng <chaohengmeng@163.com>
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MC_ROLL_P 6.5
param set-default MC_ROLLRATE_P 0.064
param set-default MC_ROLLRATE_I 0.085
param set-default MC_ROLLRATE_D 0.0016
param set-default MC_ROLLRATE_FF 0

param set-default MC_PITCH_P 5.9
param set-default MC_PITCHRATE_P 0.142
param set-default MC_PITCHRATE_I 0.19
param set-default MC_PITCHRATE_D 0.0032
param set-default MC_PITCHRATE_FF 0

param set-default MC_YAW_P 6.5
param set-default MC_YAWRATE_P 0.1
param set-default MC_YAWRATE_I 0.1
param set-default MC_YAWRATE_D 0.0
param set-default MC_YAWRATE_FF 0

param set-default MPC_Z_VEL_P_ACC 4.5
param set-default MPC_Z_VEL_I_ACC 0.7
param set-default MPC_Z_VEL_D_ACC 0.3
param set-default MPC_Z_P 0.6
param set-default MPC_XY_VEL_P_ACC 2
param set-default MPC_XY_VEL_I_ACC 1.0
param set-default MPC_XY_VEL_D_ACC 0.1
param set-default MPC_XY_P 0.45

set MIXER flyant
