#!/bin/sh
#
# @name SHC09
#
# @type Ducted Fan
#
# Author: Chaoheng Meng <chaohengmeng@163.com>



. ${R}etc/init.d/rc.mc_defaults
set VEHICLE_TYPE df

param set-default CA_AIRFRAME 16
# SHC09 stores physical effectiveness values; Ducted Fan keeps the allocator
# contract normalized for both PID and INDI.

param set-default DF_ROLLRATE_P 0.4
param set-default DF_ROLLRATE_I 0.2

param set-default DF_PITCHRATE_P 0.4
param set-default DF_PITCHRATE_I 0.2

param set-default DF_YAWRATE_P 0.2
param set-default DF_YAWRATE_I 0.1

param set-default MPC_THR_HOVER 0.5
param set-default RTL_RETURN_ALT 2.5
param set-default RTL_DESCEND_ALT 2.5


param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_AX 0
param set-default CA_ROTOR0_AY 0
param set-default CA_ROTOR0_AZ -1
param set-default CA_ROTOR0_PX 0
param set-default CA_ROTOR0_PY 0
param set-default CA_ROTOR0_PZ -0.045
param set-default CA_ROTOR0_CT 6.5
param set-default CA_ROTOR0_KM 0

# Physical surface model from df-1.12.3 SHC09.main.mix.
# B maps control-surface deflection in radians to angular acceleration.
# DF_CS_MAX maps +/-0.6981 rad to normalized actuator_servos +/-1.
param set-default DF_CS_MAX 0.6981
param set-default DF_ACTUATOR 1
param set-default DF_TIME_CONST 0.01
param set-default DF_CS_CUTOFF 8
param set-default CA_SV_CS_COUNT 6
param set-default CA_SV_CS0_TRQ_R -12.8740
param set-default CA_SV_CS0_TRQ_P 0
param set-default CA_SV_CS0_TRQ_Y 28.4137
param set-default CA_SV_CS1_TRQ_R -6.4370
param set-default CA_SV_CS1_TRQ_P 11.2003
param set-default CA_SV_CS1_TRQ_Y 28.4137
param set-default CA_SV_CS2_TRQ_R 6.4370
param set-default CA_SV_CS2_TRQ_P 11.2003
param set-default CA_SV_CS2_TRQ_Y 28.4137
param set-default CA_SV_CS3_TRQ_R 12.8740
param set-default CA_SV_CS3_TRQ_P 0
param set-default CA_SV_CS3_TRQ_Y 28.4137
param set-default CA_SV_CS4_TRQ_R 6.4370
param set-default CA_SV_CS4_TRQ_P -11.2003
param set-default CA_SV_CS4_TRQ_Y 28.4137
param set-default CA_SV_CS5_TRQ_R -6.4370
param set-default CA_SV_CS5_TRQ_P -11.2003
param set-default CA_SV_CS5_TRQ_Y 28.4137

# param set-default VT_ELEV_MC_LOCK 0

param set-default PWM_MAIN_FUNC1 101

param set-default PWM_MAIN_FUNC2 201
param set-default PWM_MAIN_FUNC3 202
param set-default PWM_MAIN_FUNC4 203
param set-default PWM_MAIN_FUNC5 204
param set-default PWM_MAIN_FUNC6 205
param set-default PWM_MAIN_FUNC7 206

param set-default SDLOG_PROFILE 17
param set-default SDLOG_MODE 0
