#!/bin/sh
#
# @name SHW09_vtol
#
# @type VTOL Ducted Fan



. ${R}etc/init.d/rc.vtol_defaults

param set-default MAV_TYPE 19 # For MAVLink

param set-default EKF2_FUSE_BETA 0 # side slip fusion is currently not supported for tailsitters

param set-default CA_AIRFRAME 4 # have to used 4 for FW-mode

param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_AX 0
param set-default CA_ROTOR0_AY 0
param set-default CA_ROTOR0_AZ -1
param set-default CA_ROTOR0_PX 0
param set-default CA_ROTOR0_PY 0
param set-default CA_ROTOR0_PZ -0.0
param set-default CA_ROTOR0_KM 0.05

param set-default CA_SV_CS_COUNT 8
param set-default CA_SV_CS0_TRQ_R -0.501
param set-default CA_SV_CS0_TRQ_P 0
param set-default CA_SV_CS0_TRQ_Y 0.207
param set-default CA_SV_CS1_TRQ_R -0.2505
param set-default CA_SV_CS1_TRQ_P -0.4339
param set-default CA_SV_CS1_TRQ_Y 0.207
param set-default CA_SV_CS2_TRQ_R 0.2505
param set-default CA_SV_CS2_TRQ_P -0.4339
param set-default CA_SV_CS2_TRQ_Y 0.207
param set-default CA_SV_CS3_TRQ_R 0.501
param set-default CA_SV_CS3_TRQ_P 0
param set-default CA_SV_CS3_TRQ_Y 0.207
param set-default CA_SV_CS4_TRQ_R 0.2505
param set-default CA_SV_CS4_TRQ_P 0.4339
param set-default CA_SV_CS4_TRQ_Y 0.207
param set-default CA_SV_CS5_TRQ_R -0.2505
param set-default CA_SV_CS5_TRQ_P 0.4339
param set-default CA_SV_CS5_TRQ_Y 0.207

param set-default CA_SV_CS6_TYPE 0
param set-default CA_SV_CS6_TRQ_P -0.5
param set-default CA_SV_CS6_TRQ_Y 0.5
param set-default CA_SV_CS7_TYPE 0
param set-default CA_SV_CS7_TRQ_P -0.5
param set-default CA_SV_CS7_TRQ_Y -0.5

param set-default VT_ELEV_MC_LOCK 0
param set-default VT_TS_CS_HVR_DIS 192

param set-default MC_ROLL_P 6
param set-default MC_ROLLRATE_P 0.45
param set-default MC_ROLLRATE_I 0.3
param set-default MC_ROLLRATE_D 0.0
param set-default MC_ROLLRATE_FF 0

param set-default MC_PITCH_P 6
param set-default MC_PITCHRATE_P 0.45
param set-default MC_PITCHRATE_I 0.3
param set-default MC_PITCHRATE_D 0.0
param set-default MC_PITCHRATE_FF 0

param set-default MC_YAW_P 5
param set-default MC_YAWRATE_P 0.4
param set-default MC_YAWRATE_I 0.3
param set-default MC_YAWRATE_D 0
param set-default MC_YAWRATE_FF 0

param set-default MPC_THR_HOVER 0.75

param set-default PWM_MAIN_FUNC1 101

param set-default PWM_MAIN_FUNC2 201
param set-default PWM_MAIN_FUNC3 202
param set-default PWM_MAIN_FUNC4 203
param set-default PWM_MAIN_FUNC5 204
param set-default PWM_MAIN_FUNC6 205
param set-default PWM_MAIN_FUNC7 206
param set-default PWM_MAIN_FUNC8 207
param set-default PWM_MAIN_FUNC9 208

# Single-EKF (for replay)
param set-default EKF2_MULTI_IMU 0
param set-default SENS_IMU_MODE 1

param set-default FW_PR_FF 0.0
param set-default FW_PSP_OFF 5
param set-default MC_AIRMODE 1
param set-default FW_THR_TRIM 0.40
param set-default FW_THR_MIN 0.2


param set-default VT_ARSP_TRANS 10
param set-default VT_B_TRANS_DUR 3
param set-default VT_F_TRANS_DUR 2
param set-default VT_TYPE 0

param set-default WV_EN 0

param set-default SDLOG_PROFILE 17
param set-default SDLOG_MODE 0
