#!/bin/sh
#
# @name SHW09_vtol
#
# @type VTOL Ducted Fan



. ${R}etc/init.d/rc.vtol_defaults

param set-default MAV_TYPE 20

param set-default EKF2_FUSE_BETA 0 # side slip fusion is currently not supported for tailsitters

param set-default CA_AIRFRAME 4

param set-default MC_ROLL_P 6
param set-default MC_ROLLRATE_P 0.45
param set-default MC_ROLLRATE_I 0.3
param set-default MC_ROLLRATE_D 0.0
param set-default MC_ROLLRATE_FF 0

param set-default MC_PITCH_P 6
param set-default MC_PITCHRATE_P 0.45
param set-default MC_PITCHRATE_I 0.3
param set-default MC_PITCHRATE_D 0.0
param set-default MC_PITCHRATE_FF 0

param set-default MC_YAW_P 5
param set-default MC_YAWRATE_P 0.4
param set-default MC_YAWRATE_I 0.3
param set-default MC_YAWRATE_D 0
param set-default MC_YAWRATE_FF 0

param set-default MPC_THR_HOVER 0.5

param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_AX 0
param set-default CA_ROTOR0_AY 0
param set-default CA_ROTOR0_AZ -1
param set-default CA_ROTOR0_PX 0
param set-default CA_ROTOR0_PY 0
param set-default CA_ROTOR0_PZ -0.045
param set-default CA_ROTOR0_KM 0.05

param set-default CA_SV_CS_COUNT 8
param set-default CA_SV_CS0_TRQ_R -0.501
param set-default CA_SV_CS0_TRQ_P 0
param set-default CA_SV_CS0_TRQ_Y 0.207
param set-default CA_SV_CS1_TRQ_R -0.2505
param set-default CA_SV_CS1_TRQ_P -0.4339
param set-default CA_SV_CS1_TRQ_Y 0.207
param set-default CA_SV_CS2_TRQ_R 0.2505
param set-default CA_SV_CS2_TRQ_P -0.4339
param set-default CA_SV_CS2_TRQ_Y 0.207
param set-default CA_SV_CS3_TRQ_R 0.501
param set-default CA_SV_CS3_TRQ_P 0
param set-default CA_SV_CS3_TRQ_Y 0.207
param set-default CA_SV_CS4_TRQ_R 0.2505
param set-default CA_SV_CS4_TRQ_P 0.4339
param set-default CA_SV_CS4_TRQ_Y 0.207
param set-default CA_SV_CS5_TRQ_R -0.2505
param set-default CA_SV_CS5_TRQ_P 0.4339
param set-default CA_SV_CS5_TRQ_Y 0.207

param set-default CA_SV_CS6_TYPE 5
param set-default CA_SV_CS6_TRQ_P 0.533
param set-default CA_SV_CS6_TRQ_Y -0.533
param set-default CA_SV_CS7_TYPE 6
param set-default CA_SV_CS7_TRQ_P 0.533
param set-default CA_SV_CS7_TRQ_Y 0.533

param set-default PWM_MAIN_FUNC1 101

param set-default PWM_MAIN_FUNC2 201
param set-default PWM_MAIN_FUNC3 202
param set-default PWM_MAIN_FUNC4 203
param set-default PWM_MAIN_FUNC5 204
param set-default PWM_MAIN_FUNC6 205
param set-default PWM_MAIN_FUNC7 206
param set-default PWM_MAIN_FUNC8 207
param set-default PWM_MAIN_FUNC9 208


param set-default VT_TYPE 0

param set-default WV_EN 0

