#!/bin/sh
#
# @name ductedfan2
#
# @type Ducted Fan



. ${R}etc/init.d/rc.mc_defaults

param set-default CA_AIRFRAME 9

param set-default MC_ROLL_P 6.5
param set-default MC_ROLLRATE_P 0.45
param set-default MC_ROLLRATE_I 0.1
param set-default MC_ROLLRATE_D 0.01
param set-default MC_ROLLRATE_FF 0
param set-default MC_PITCH_P 6.5
param set-default MC_PITCHRATE_P 0.45
param set-default MC_PITCHRATE_I 0.05
param set-default MC_PITCHRATE_D 0.01
param set-default MC_PITCHRATE_FF 0
param set-default MC_YAW_P 2
param set-default MC_YAWRATE_P 0.3
param set-default MC_YAWRATE_I 0.05
param set-default MC_YAWRATE_D 0
param set-default MC_YAWRATE_FF 0

param set-default MPC_THR_HOVER 0.5
param set-default RTL_RETURN_ALT 2.5
param set-default RTL_DESCEND_ALT 2.5

param set-default CA_ROTOR_COUNT 2
param set-default CA_ROTOR0_AX 0
param set-default CA_ROTOR0_AY 0
param set-default CA_ROTOR0_AZ -1
param set-default CA_ROTOR0_PX 0
param set-default CA_ROTOR0_PY 0
param set-default CA_ROTOR0_PZ -0.045
param set-default CA_ROTOR0_KM -0.05

param set-default CA_ROTOR1_AX 0
param set-default CA_ROTOR1_AY 0
param set-default CA_ROTOR1_AZ -1
param set-default CA_ROTOR1_PX 0
param set-default CA_ROTOR1_PY 0
param set-default CA_ROTOR1_PZ -0.1
param set-default CA_ROTOR1_KM 0.05



param set-default CA_SV_CS_COUNT 2
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS0_TRQ_P 0
param set-default CA_SV_CS0_TRQ_Y 0
param set-default CA_SV_CS1_TRQ_R 0
param set-default CA_SV_CS1_TRQ_P 0.5
param set-default CA_SV_CS1_TRQ_Y 0


param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 201
param set-default PWM_MAIN_FUNC4 202

param set-default SDLOG_PROFILE 17
param set-default SDLOG_MODE 0
