#!/bin/sh
#
# @name Gazebo ductedfan4
#
# @type Ducted Fan
#
# Author: Chaoheng Meng <chaohengmeng@163.com>


. ${R}etc/init.d/rc.mc_defaults
PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=ductedfan4}

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 16 # 9(NormalizeRPY=0)

# Effectiveness unit contract (control_allocation/df4.m):
#   v = [tau; F] = B*u, with tau [N m], F [N]. The physical actuator vector u
#   contains rotor thrust [N] and surface deflection [rad]. Parameters use
#   u = U*u_norm, so PX4 is configured with B*U and allocates
#   v = (B*U)*u_norm. CA_ROTOR0_CT is maximum thrust [N]; each
#   CA_SV_CSx_TRQ_* is the moment at normalized surface command +1 [N m] and
#   already includes the 20 deg maximum deflection. Do not multiply another
#   motor-thrust or surface-deflection scale in control_allocator.

param set-default MC_ROLL_P 4
param set-default MC_ROLLRATE_P 0.45
param set-default MC_ROLLRATE_I 0.3
param set-default MC_ROLLRATE_D 0.0
param set-default MC_ROLLRATE_FF 0

param set-default MC_PITCH_P 4
param set-default MC_PITCHRATE_P 0.45
param set-default MC_PITCHRATE_I 0.3
param set-default MC_PITCHRATE_D 0.0
param set-default MC_PITCHRATE_FF 0

param set-default MC_YAW_P 2.8
param set-default MC_YAWRATE_P 0.4
param set-default MC_YAWRATE_I 0.3
param set-default MC_YAWRATE_D 0
param set-default MC_YAWRATE_FF 0

# The 1.56 kg model hovers at motor signal x=0.7146. With the quadratic
# thrust model MPC_THR_HOVER=x^2 and Fmax=mass*g/MPC_THR_HOVER.
param set-default MPC_THR_HOVER 0.510653
param set-default THR_MDL_FAC 1
param set-default RTL_RETURN_ALT 2.5
param set-default RTL_DESCEND_ALT 2.5

param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_AX 0
param set-default CA_ROTOR0_AY 0
param set-default CA_ROTOR0_AZ -1
param set-default CA_ROTOR0_PX 0
param set-default CA_ROTOR0_PY 0
param set-default CA_ROTOR0_PZ 0.05
param set-default CA_ROTOR0_CT 29.9584
param set-default CA_ROTOR0_KM 0

param set-default CA_SV_CS_COUNT 4
param set-default CA_FORCE_CUTOFF 5
param set-default CA_TORQ_CUTOFF 8
param set-default IMU_DGYRO_CUTOFF 10
param set-default MPC_MASS 1.56
param set-default MC_J_X 0.01149
param set-default MC_J_Y 0.01153
param set-default MC_J_Z 0.00487

param set-default MC_ATT_ERR_MODE 3
param set-default MC_YAW_WEIGHT 1 # K_YAW=MC_YAW_P/MC_YAW_WEIGHT

param set-default CA_SV_CS0_TRQ_R -0.166227
param set-default CA_SV_CS0_TRQ_P 0
param set-default CA_SV_CS0_TRQ_Y 0.068681
param set-default CA_SV_CS1_TRQ_R 0
param set-default CA_SV_CS1_TRQ_P -0.166227
param set-default CA_SV_CS1_TRQ_Y 0.068681
param set-default CA_SV_CS2_TRQ_R 0.166227
param set-default CA_SV_CS2_TRQ_P 0
param set-default CA_SV_CS2_TRQ_Y 0.068681
param set-default CA_SV_CS3_TRQ_R 0
param set-default CA_SV_CS3_TRQ_P 0.166227
param set-default CA_SV_CS3_TRQ_Y 0.068681


param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MAX1 1750

param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204

param set-default SIM_GZ_SV_MINA1 -20
param set-default SIM_GZ_SV_MAXA1 20
param set-default SIM_GZ_SV_MINA2 20
param set-default SIM_GZ_SV_MAXA2 -20
param set-default SIM_GZ_SV_MINA3 20
param set-default SIM_GZ_SV_MAXA3 -20
param set-default SIM_GZ_SV_MINA4 -20
param set-default SIM_GZ_SV_MAXA4 20

param set-default SDLOG_PROFILE 27
param set-default SDLOG_MODE 0
