#!/bin/sh
#
# @name Gazebo ductedfan2
#
# @type Ducted Fan
#
# Author: Chaoheng Meng <chaohengmeng@163.com>

. ${R}etc/init.d/rc.mc_defaults
set VEHICLE_TYPE mc

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=ductedfan2}

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 9

param set-default MC_ROLL_P 6.5
param set-default MC_ROLLRATE_P 0.45
param set-default MC_ROLLRATE_I 0.1
param set-default MC_ROLLRATE_D 0.01
param set-default MC_ROLLRATE_FF 0

param set-default MC_PITCH_P 6.5
param set-default MC_PITCHRATE_P 0.45
param set-default MC_PITCHRATE_I 0.05
param set-default MC_PITCHRATE_D 0.01
param set-default MC_PITCHRATE_FF 0

param set-default MC_YAW_P 2
param set-default MC_YAWRATE_P 0.3
param set-default MC_YAWRATE_I 0.05
param set-default MC_YAWRATE_D 0
param set-default MC_YAWRATE_FF 0

param set-default MPC_THR_HOVER 0.5
param set-default RTL_RETURN_ALT 2.5
param set-default RTL_DESCEND_ALT 2.5

param set-default CA_ROTOR_COUNT 2
param set-default CA_ROTOR0_AX 0
param set-default CA_ROTOR0_AY 0
param set-default CA_ROTOR0_AZ -1
param set-default CA_ROTOR0_PX 0
param set-default CA_ROTOR0_PY 0
param set-default CA_ROTOR0_PZ -0.045
param set-default CA_ROTOR0_KM -0.05

param set-default CA_ROTOR1_AX 0
param set-default CA_ROTOR1_AY 0
param set-default CA_ROTOR1_AZ -1
param set-default CA_ROTOR1_PX 0
param set-default CA_ROTOR1_PY 0
param set-default CA_ROTOR1_PZ -0.1
param set-default CA_ROTOR1_KM 0.05

param set-default CA_SV_CS_COUNT 2
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS0_TRQ_P 0
param set-default CA_SV_CS0_TRQ_Y 0
param set-default CA_SV_CS1_TRQ_R 0
param set-default CA_SV_CS1_TRQ_P 0.5
param set-default CA_SV_CS1_TRQ_Y 0

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MAX1 1500

param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_MIN2 0
param set-default SIM_GZ_EC_MAX2 1500

param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202

param set-default SIM_GZ_SV_MINA1 -20.0535
param set-default SIM_GZ_SV_MAXA1 20.0535
param set-default SIM_GZ_SV_MINA2 -20.0535
param set-default SIM_GZ_SV_MAXA2 20.0535

param set-default SDLOG_PROFILE 17
param set-default SDLOG_MODE 0
