#!/bin/sh
#
# @name ductedfan4
#
# @type Ducted Fan
#
# Author: Chaoheng Meng <chaohengmeng@163.com>



. ${R}etc/init.d/rc.mc_defaults
param set-default CA_AIRFRAME 16 # matrix 0: physical force, matrix 1: physical torque

# CA16 publishes physical allocation feedback. mc_pos_control reads force from
# allocation instance 0; mc_rate_control reads torque from allocation instance 1.
#
# Effectiveness unit contract (control_allocation/df4.m):
#   v = [tau; F] = B*u, with tau [N m], F [N]. The physical actuator vector u
#   contains rotor thrust [N] and surface deflection [rad]. Parameters use
#   u = U*u_norm, so PX4 is configured with B*U and allocates
#   v = (B*U)*u_norm. CA_ROTOR0_CT is maximum thrust [N]; each
#   CA_SV_CSx_TRQ_* is the moment at normalized surface command +1 [N m] and
#   already includes the 20 deg maximum deflection. Do not multiply another
#   motor-thrust or surface-deflection scale in control_allocator.

param set-default MC_ROLL_P 4
param set-default MC_ROLLRATE_P 0.45
param set-default MC_ROLLRATE_I 0.3
param set-default MC_ROLLRATE_D 0.0
param set-default MC_ROLLRATE_FF 0

param set-default MC_PITCH_P 4
param set-default MC_PITCHRATE_P 0.45
param set-default MC_PITCHRATE_I 0.3
param set-default MC_PITCHRATE_D 0.0
param set-default MC_PITCHRATE_FF 0

param set-default MC_YAW_P 2.8
param set-default MC_YAWRATE_P 0.4
param set-default MC_YAWRATE_I 0.3
param set-default MC_YAWRATE_D 0
param set-default MC_YAWRATE_FF 0
param set-default MC_YAW_TQ_CUTOFF 0

param set-default MC_ATT_ERR_MODE 3
param set-default MC_YAW_WEIGHT 1 # K_YAW=MC_YAW_P/MC_YAW_WEIGHT
param set-default MPC_YAWRAUTO_ACC 180
param set-default MPC_YAWRAUTO_MAX 90

# 1. Rate INDI: angular acceleration feedback alpha_0
param set-default IMU_GYRO_CUTOFF 110
param set-default IMU_DGYRO_CUTOFF 10

# Rate INDI: allocated physical torque feedback tau_0
param set-default CA_TORQ_CUTOFF 8

# Rate INDI: inertia model
param set-default MC_J_X 0.01149
param set-default MC_J_Y 0.01153
param set-default MC_J_Z 0.00487

# 2. Acc INDI: selected acceleration source
param set-default MPC_INDI_A_SRC 1

# SRC 0: velocity derivative
param set-default MPC_VEL_LP 0
param set-default MPC_VELD_LP 5
param set-default MPC_VEL_NF_FRQ 0
param set-default MPC_VEL_NF_BW 20

# SRC 1 and SRC 2: direct acceleration candidates
param set-default MPC_INDI_A_LP 10

# SRC 2 upstream vehicle_acceleration filter
param set-default IMU_ACCEL_CUTOFF 30

# Acc INDI: physical force feedback F_0
param set-default CA_FORCE_CUTOFF 6
param set-default MPC_INDI_F_DLY 0.05

# Acc INDI: mass/force model
param set-default MPC_MASS 1.56


# The 1.56 kg model hovers at motor signal x=0.7146. With the quadratic
# thrust model MPC_THR_HOVER=x^2 and Fmax=mass*g/MPC_THR_HOVER.
param set-default MPC_THR_HOVER 0.510653
param set-default THR_MDL_FAC 1
param set-default RTL_RETURN_ALT 2.5
param set-default RTL_DESCEND_ALT 2.5

param set-default MC_F8_ACC 10
param set-default MC_F8_AX 5
param set-default MC_F8_AY 2.5
param set-default MC_F8_AZ 0
param set-default MC_F8_OMEGA 0.4
param set-default MC_ORBIT_YAW_MOD 3

param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_AX 0
param set-default CA_ROTOR0_AY 0
param set-default CA_ROTOR0_AZ -1
param set-default CA_ROTOR0_PX 0
param set-default CA_ROTOR0_PY 0
param set-default CA_ROTOR0_PZ 0.05
param set-default CA_ROTOR0_CT 29.9584
param set-default CA_ROTOR0_KM 0

param set-default CA_SV_CS_COUNT 4
param set-default CA_SV_CS0_TRQ_R -0.166227
param set-default CA_SV_CS0_TRQ_P 0
param set-default CA_SV_CS0_TRQ_Y 0.068681
param set-default CA_SV_CS1_TRQ_R 0
param set-default CA_SV_CS1_TRQ_P -0.166227
param set-default CA_SV_CS1_TRQ_Y 0.068681
param set-default CA_SV_CS2_TRQ_R 0.166227
param set-default CA_SV_CS2_TRQ_P 0
param set-default CA_SV_CS2_TRQ_Y 0.068681
param set-default CA_SV_CS3_TRQ_R 0
param set-default CA_SV_CS3_TRQ_P 0.166227
param set-default CA_SV_CS3_TRQ_Y 0.068681

param set-default PWM_MAIN_FUNC1 101

param set-default PWM_MAIN_FUNC2 201
param set-default PWM_MAIN_FUNC3 202
param set-default PWM_MAIN_FUNC4 203
param set-default PWM_MAIN_FUNC5 204

param set-default SDLOG_PROFILE 27
param set-default SDLOG_MODE 0
