#!/bin/sh
#
# @name ductedfan4
#
# @type Ducted Fan
#
# Author: Chaoheng Meng <chaohengmeng@163.com>



. ${R}etc/init.d/rc.mc_defaults
param set-default CA_AIRFRAME 16 # matrix 0: physical force, matrix 1: physical torque

# CA16 publishes physical allocation feedback. mc_pos_control reads force from
# allocation instance 0; mc_rate_control reads torque from allocation instance 1.
#
# Effectiveness unit contract (control_allocation/df4.m):
#   v = [tau; F] = B*u, with tau [N m], F [N]. The physical actuator vector u
#   contains rotor thrust [N] and surface deflection [rad]. Parameters use
#   u = U*u_norm, so PX4 is configured with B*U and allocates
#   v = (B*U)*u_norm. CA_ROTOR0_CT is maximum thrust [N]; each
#   CA_SV_CSx_TRQ_* is the moment at normalized surface command +1 [N m] and
#   already includes the 20 deg maximum deflection. Do not multiply another
#   motor-thrust or surface-deflection scale in control_allocator.

param set-default MC_ROLL_P 4
param set-default MC_ROLLRATE_P 0.45
param set-default MC_ROLLRATE_I 0.3
param set-default MC_ROLLRATE_D 0.0
param set-default MC_ROLLRATE_FF 0

param set-default MC_PITCH_P 4
param set-default MC_PITCHRATE_P 0.45
param set-default MC_PITCHRATE_I 0.3
param set-default MC_PITCHRATE_D 0.0
param set-default MC_PITCHRATE_FF 0

param set-default MC_YAW_P 2.8
param set-default MC_YAWRATE_P 0.4
param set-default MC_YAWRATE_I 0.3
param set-default MC_YAWRATE_D 0
param set-default MC_YAWRATE_FF 0

param set-default MPC_YAWRAUTO_ACC 180
param set-default MPC_YAWRAUTO_MAX 90
param set-default MC_F8_ACC 10
param set-default MC_F8_VEL 2
param set-default MC_ORBIT_YAW_MOD 3

param set-default MPC_THR_HOVER 0.49
param set-default THR_MDL_FAC 1
param set-default RTL_RETURN_ALT 2.5
param set-default RTL_DESCEND_ALT 2.5

param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_AX 0
param set-default CA_ROTOR0_AY 0
param set-default CA_ROTOR0_AZ -1
param set-default CA_ROTOR0_PX 0
param set-default CA_ROTOR0_PY 0
param set-default CA_ROTOR0_PZ 0.05
param set-default CA_ROTOR0_CT 27.8
param set-default CA_ROTOR0_KM 0

param set-default CA_SV_CS_COUNT 4
param set-default CA_FORCE_CUTOFF 6
param set-default CA_TORQ_CUTOFF 8
param set-default IMU_DGYRO_CUTOFF 10
param set-default MPC_MASS 1.39
param set-default MC_J_X 0.01149
param set-default MC_J_Y 0.01153
param set-default MC_J_Z 0.00487

param set-default MC_ATT_ERR_MODE 3
param set-default MC_YAW_WEIGHT 1 # K_YAW=MC_YAW_P/MC_YAW_WEIGHT

param set-default CA_SV_CS0_TRQ_R -0.166227
param set-default CA_SV_CS0_TRQ_P 0
param set-default CA_SV_CS0_TRQ_Y 0.068681
param set-default CA_SV_CS1_TRQ_R 0
param set-default CA_SV_CS1_TRQ_P -0.166227
param set-default CA_SV_CS1_TRQ_Y 0.068681
param set-default CA_SV_CS2_TRQ_R 0.166227
param set-default CA_SV_CS2_TRQ_P 0
param set-default CA_SV_CS2_TRQ_Y 0.068681
param set-default CA_SV_CS3_TRQ_R 0
param set-default CA_SV_CS3_TRQ_P 0.166227
param set-default CA_SV_CS3_TRQ_Y 0.068681

param set-default PWM_MAIN_FUNC1 101

param set-default PWM_MAIN_FUNC2 201
param set-default PWM_MAIN_FUNC3 202
param set-default PWM_MAIN_FUNC4 203
param set-default PWM_MAIN_FUNC5 204

param set-default SDLOG_PROFILE 27
param set-default SDLOG_MODE 0
