#!/bin/sh
#
# @name ductedfan_mini
#
# @type Ducted Fan
#
# Author: Chaoheng Meng <chaohengmeng@163.com>



. ${R}etc/init.d/rc.mc_defaults
# This legacy CA_AIRFRAME=9 profile uses one allocation matrix, so keep the
# standard multicopter controller routing (torque and thrust on instance 0).
set VEHICLE_TYPE mc

param set-default CA_AIRFRAME 9 #   9 or 16

# Target physical effectiveness contract:
#   v = [tau; F] = B*u, with tau [N m], F [N]. Physical u contains rotor
#   thrust [N] and surface deflection [rad]. Parameters are entered after
#   u = U*u_norm, so CA_ROTOR*/CA_SV_CS* together represent B*U and allocation
#   uses v = (B*U)*u_norm. However, this CA_AIRFRAME=9 profile still contains a
#   legacy normalized shape matrix, not calibrated forces [N] and moments [N m].
#   Do not enable physical-wrench INDI until CT and surface moments are identified
#   and the allocator source provides matching normalization and feedback.

param set-default MC_ROLL_P 6
param set-default MC_ROLLRATE_P 0.45
param set-default MC_ROLLRATE_I 0.3
param set-default MC_ROLLRATE_D 0.0
param set-default MC_ROLLRATE_FF 0

param set-default MC_PITCH_P 6
param set-default MC_PITCHRATE_P 0.45
param set-default MC_PITCHRATE_I 0.3
param set-default MC_PITCHRATE_D 0.0
param set-default MC_PITCHRATE_FF 0

param set-default MC_YAW_P 5
param set-default MC_YAWRATE_P 0.4
param set-default MC_YAWRATE_I 0.3
param set-default MC_YAWRATE_D 0
param set-default MC_YAWRATE_FF 0

param set-default MPC_THR_HOVER 0.5
param set-default RTL_RETURN_ALT 2.5
param set-default RTL_DESCEND_ALT 2.5

param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_AX 0
param set-default CA_ROTOR0_AY 0
param set-default CA_ROTOR0_AZ -1
param set-default CA_ROTOR0_PX 0
param set-default CA_ROTOR0_PY 0
param set-default CA_ROTOR0_PZ 0.01
param set-default CA_ROTOR0_KM 0.05

param set-default CA_SV_CS_COUNT 4
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS0_TRQ_P 0
param set-default CA_SV_CS0_TRQ_Y 0.25
param set-default CA_SV_CS1_TRQ_R 0
param set-default CA_SV_CS1_TRQ_P -0.5
param set-default CA_SV_CS1_TRQ_Y 0.25
param set-default CA_SV_CS2_TRQ_R 0.5
param set-default CA_SV_CS2_TRQ_P 0
param set-default CA_SV_CS2_TRQ_Y 0.25
param set-default CA_SV_CS3_TRQ_R 0
param set-default CA_SV_CS3_TRQ_P 0.5
param set-default CA_SV_CS3_TRQ_Y 0.25

param set-default PWM_MAIN_FUNC1 101

param set-default PWM_MAIN_FUNC2 201
param set-default PWM_MAIN_FUNC3 202
param set-default PWM_MAIN_FUNC4 203
param set-default PWM_MAIN_FUNC5 204

# param set-default SDLOG_PROFILE 17
param set-default SDLOG_MODE 0
