#!/bin/sh
#
# @name Gazebo SHC09
#
# @type Ducted Fan
#
# Author: Chaoheng Meng <chaohengmeng@163.com>

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=SHC09}

param set-default SIM_GZ_EN 1

param set-default CA_AIRFRAME 9

param set-default MC_ROLLRATE_P 0.4
param set-default MC_ROLLRATE_I 0.2

param set-default MC_PITCHRATE_P 0.4
param set-default MC_PITCHRATE_I 0.2

param set-default MC_YAWRATE_P 0.2
param set-default MC_YAWRATE_I 0.1

param set-default MC_PITCH_P 5
param set-default MC_ROLL_P 5
param set-default MC_YAW_P 3

param set-default MPC_THR_HOVER 0.49
param set-default THR_MDL_FAC 1
param set-default RTL_RETURN_ALT 2.5
param set-default RTL_DESCEND_ALT 2.5

param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_AX 0
param set-default CA_ROTOR0_AY 0
param set-default CA_ROTOR0_AZ -1
param set-default CA_ROTOR0_PX 0
param set-default CA_ROTOR0_PY 0
param set-default CA_ROTOR0_PZ 0.1
param set-default CA_ROTOR0_CT 1
param set-default CA_ROTOR0_KM 0


param set-default CA_SV_CS_COUNT 6
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS0_TRQ_P 0
param set-default CA_SV_CS0_TRQ_Y 0.207
param set-default CA_SV_CS1_TRQ_R -0.25
param set-default CA_SV_CS1_TRQ_P 0.433
param set-default CA_SV_CS1_TRQ_Y 0.207
param set-default CA_SV_CS2_TRQ_R 0.25
param set-default CA_SV_CS2_TRQ_P 0.433
param set-default CA_SV_CS2_TRQ_Y 0.207
param set-default CA_SV_CS3_TRQ_R 0.5
param set-default CA_SV_CS3_TRQ_P 0
param set-default CA_SV_CS3_TRQ_Y 0.207
param set-default CA_SV_CS4_TRQ_R 0.25
param set-default CA_SV_CS4_TRQ_P -0.433
param set-default CA_SV_CS4_TRQ_Y 0.207
param set-default CA_SV_CS5_TRQ_R -0.25
param set-default CA_SV_CS5_TRQ_P -0.433
param set-default CA_SV_CS5_TRQ_Y 0.207


param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MAX1 1200

param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204
param set-default SIM_GZ_SV_FUNC5 205
param set-default SIM_GZ_SV_FUNC6 206

param set-default SIM_GZ_SV_MINA1 -40
param set-default SIM_GZ_SV_MAXA1 40
param set-default SIM_GZ_SV_MINA2 -40
param set-default SIM_GZ_SV_MAXA2 40
param set-default SIM_GZ_SV_MINA3 -40
param set-default SIM_GZ_SV_MAXA3 40
param set-default SIM_GZ_SV_MINA4 -40
param set-default SIM_GZ_SV_MAXA4 40
param set-default SIM_GZ_SV_MINA5 -40
param set-default SIM_GZ_SV_MAXA5 40
param set-default SIM_GZ_SV_MINA6 -40
param set-default SIM_GZ_SV_MAXA6 40

param set-default SDLOG_PROFILE 1
param set-default SDLOG_MODE 0
