#!/bin/sh
#
# @name Gazebo SHW09_vtol
#
# @type VTOL Tailsitter
#
# Author: Chaoheng Meng <chaohengmeng@163.com>

. ${R}etc/init.d/rc.vtol_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=SHW09_vtol}

param set-default SIM_GZ_EN 1

param set-default MAV_TYPE 19
param set-default EKF2_FUSE_BETA 0
param set-default CA_AIRFRAME 4

param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_AX 0
param set-default CA_ROTOR0_AY 0
param set-default CA_ROTOR0_AZ -1
param set-default CA_ROTOR0_PX 0
param set-default CA_ROTOR0_PY 0
param set-default CA_ROTOR0_PZ -0.0
param set-default CA_ROTOR0_CT 1
param set-default CA_ROTOR0_KM 0.05

param set-default CA_SV_CS_COUNT 8
param set-default CA_SV_CS0_TRQ_R -0.501
param set-default CA_SV_CS0_TRQ_P 0
param set-default CA_SV_CS0_TRQ_Y 0.207
param set-default CA_SV_CS1_TRQ_R -0.2505
param set-default CA_SV_CS1_TRQ_P 0.4339
param set-default CA_SV_CS1_TRQ_Y 0.207
param set-default CA_SV_CS2_TRQ_R 0.2505
param set-default CA_SV_CS2_TRQ_P 0.4339
param set-default CA_SV_CS2_TRQ_Y 0.207
param set-default CA_SV_CS3_TRQ_R 0.501
param set-default CA_SV_CS3_TRQ_P 0
param set-default CA_SV_CS3_TRQ_Y 0.207
param set-default CA_SV_CS4_TRQ_R 0.2505
param set-default CA_SV_CS4_TRQ_P -0.4339
param set-default CA_SV_CS4_TRQ_Y 0.207
param set-default CA_SV_CS5_TRQ_R -0.2505
param set-default CA_SV_CS5_TRQ_P -0.4339
param set-default CA_SV_CS5_TRQ_Y 0.207
param set-default CA_SV_CS6_TYPE 0
param set-default CA_SV_CS6_TRQ_Y 0.5
param set-default CA_SV_CS7_TYPE 0
param set-default CA_SV_CS7_TRQ_Y -0.5
param set-default VT_ELEV_MC_LOCK 0

# att at MC mode
param set-default MC_ROLL_P 6
param set-default MC_PITCH_P 6
param set-default MC_YAW_P 5

# rates at MC mode, but we also use the FW rates controller for it.
param set-default MC_ROLLRATE_P 0.45
param set-default MC_ROLLRATE_I 0.3
param set-default MC_ROLLRATE_D 0.0
param set-default MC_ROLLRATE_FF 0

param set-default MC_PITCHRATE_P 0.45
param set-default MC_PITCHRATE_I 0.3
param set-default MC_PITCHRATE_D 0.0
param set-default MC_PITCHRATE_FF 0

param set-default MC_YAWRATE_P 0.4
param set-default MC_YAWRATE_I 0.3
param set-default MC_YAWRATE_D 0
param set-default MC_YAWRATE_FF 0

param set-default MPC_THR_HOVER 0.5

param set-default EKF2_MULTI_IMU 0
param set-default SENS_IMU_MODE 1

param set-default FW_ARSP_SCALE_EN 0
param set-default FW_PR_FF 0.05
param set-default FW_PR_P 0.5
param set-default FW_RR_FF 0.05
param set-default FW_RR_P 0.5
param set-default FW_YR_FF 0.04
param set-default FW_YR_P 0.4
param set-default FW_PSP_OFF 2
param set-default FW_AIRSPD_TRIM 16
param set-default FW_THR_TRIM 0.35
param set-default FW_GND_SPD_MIN 2.0
param set-default FW_T_RLL2THR 18
param set-default FW_T_ALT_TC 3.0

param set-default MC_AIRMODE 1
param set-default VT_ARSP_TRANS 10
param set-default VT_B_TRANS_DUR 3
param set-default VT_F_TRANS_DUR 3
param set-default VT_TYPE 0
param set-default WV_EN 0

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_DIS1 0
param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MAX1 1555

param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203
param set-default SIM_GZ_SV_FUNC4 204
param set-default SIM_GZ_SV_FUNC5 205
param set-default SIM_GZ_SV_FUNC6 206
param set-default SIM_GZ_SV_FUNC7 207
param set-default SIM_GZ_SV_FUNC8 208

param set-default SIM_GZ_SV_MINA1 -39.9982
param set-default SIM_GZ_SV_MAXA1 39.9982
param set-default SIM_GZ_SV_MINA2 -39.9982
param set-default SIM_GZ_SV_MAXA2 39.9982
param set-default SIM_GZ_SV_MINA3 -39.9982
param set-default SIM_GZ_SV_MAXA3 39.9982
param set-default SIM_GZ_SV_MINA4 -39.9982
param set-default SIM_GZ_SV_MAXA4 39.9982
param set-default SIM_GZ_SV_MINA5 -39.9982
param set-default SIM_GZ_SV_MAXA5 39.9982
param set-default SIM_GZ_SV_MINA6 -39.9982
param set-default SIM_GZ_SV_MAXA6 39.9982
param set-default SIM_GZ_SV_MINA7 -39.9982
param set-default SIM_GZ_SV_MAXA7 39.9982
param set-default SIM_GZ_SV_MINA8 -39.9982
param set-default SIM_GZ_SV_MAXA8 39.9982

param set-default SDLOG_PROFILE 17
param set-default SDLOG_MODE 0
