#!/bin/sh
#
# @name Ducted Fan 4 SIH
# @type Ducted Fan
# @class DuctedFan
#
# SIH counterpart of 22002_gazebo-classic_ductedfan4.
#

. ${R}etc/init.d-posix/airframes/22002_gazebo-classic_ductedfan4

# SIH INDI feedback alignment; retain the Classic gains and filters.
param set-default MC_INDI_RATE_EN 1
param set-default MPC_INDI_ACC_EN 1
param set-default MC_INDI_T_DLY 0.028
param set-default MPC_INDI_F_DLY 0.030

PX4_SIMULATOR=${PX4_SIMULATOR:=sihsim}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=ductedfan4}

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1
param set-default SENS_GPS0_DELAY 0
param set-default SENS_GPS1_DELAY 0

# Generic ducted-fan branch in simulator_sih.
param set SIH_VEHICLE_TYPE 6

# Match the current ductedfan4 Gazebo/airframe rigid-body model.
param set-default SIH_MASS 1.56
param set-default SIH_IXX 0.01149
param set-default SIH_IYY 0.01153
param set-default SIH_IZZ 0.00487
param set-default SIH_IXY 0
param set-default SIH_IXZ 0
param set-default SIH_IYZ 0

# Rotor maximum thrust for the simple DF plant, independent of allocation.
param set-default SIH_T_MAX 29.9584438

# Match the Classic motor lag; keep an independently adjustable SIH servo lag.
param set-default SIH_T_TAU 0.03

# Simple DF profile supplies slipstream vane forces and moments.
param set-default SIH_KDV 0.0
param set-default SIH_KDW 0.0

# Matched physical model and IMU noise; PID tuning is inherited above.
param set-default SIH_SV_TAU 0.03
