#!/bin/sh
#
# @name ductedfan
#
# @type Ducted Fan
# @class Copter
#
# @output MAIN1 Upper rotor (CW)
# @output MAIN2 Lower rotor (CCW)
# @output MAIN3 servomotor, roll axis
# @output MAIN4 servomotor, pitch axis
#
# @maintainer meng chaoheng
#


. ${R}etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
	param set MC_ROLL_P 6.5
	param set MC_ROLLRATE_P 0.17
	param set MC_ROLLRATE_I 0.05
	param set MC_ROLLRATE_D 0.005
	param set MC_ROLLRATE_FF 0
	param set MC_PITCH_P 6.5
	param set MC_PITCHRATE_P 0.17
	param set MC_PITCHRATE_I 0.05
	param set MC_PITCHRATE_D 0.005
	param set MC_PITCHRATE_FF 0
	param set MC_YAW_P 2
	param set MC_YAWRATE_P 0.1
	param set MC_YAWRATE_I 0.1
	param set MC_YAWRATE_D 0
	param set MC_YAWRATE_FF 0

	param set NAV_ACC_RAD 2

	param set PWM_DISARMED 900
	param set PWM_MIN 1075
	param set PWM_MAX 1950
	param set PWM_RATE 200

	param set RTL_RETURN_ALT 30
	param set RTL_DESCEND_ALT 10
fi

set MAV_TYPE 3

set MIXER ductedfan

# use PWM parameters for throttle channel
set PWM_OUT 12


