#!/bin/sh
#
# @name sductedfan
#
# @type Ducted Fan
# @class Copter
#
# @output MAIN1 Upper rotor (CCW)
# @output MAIN2 servomotor, roll axis
# @output MAIN3 servomotor, roll axis
# @output MAIN4 servomotor, pitch axis
# @output MAIN5 servomotor, pitch axis
#
# @maintainer meng chaoheng
#


. ${R}etc/init.d/rc.mc_defaults

if [ $AUTOCNF = yes ]
then
	param set MC_ROLL_P 5
	param set MC_ROLLRATE_P 0.45
	param set MC_ROLLRATE_I 0.4
	param set MC_ROLLRATE_D 0.0
	param set MC_ROLLRATE_FF 0

	param set MC_PITCH_P 5
	param set MC_PITCHRATE_P 0.45
	param set MC_PITCHRATE_I 0.4
	param set MC_PITCHRATE_D 0.0
	param set MC_PITCHRATE_FF 0

	param set MC_YAW_P 5
	param set MC_YAWRATE_P 0.4
	param set MC_YAWRATE_I 0.2
	param set MC_YAWRATE_D 0
	param set MC_YAWRATE_FF 0

	param set MC_ACRO_EXPO_Y 0
	param set MC_ACRO_EXPO 0
	param set MC_ACRO_SUPEXPO 0
	param set MC_ACRO_SUPEXPOY 0
	param set MC_ACRO_R_MAX 90.0
	param set MC_ACRO_P_MAX 90.0
	param set MC_ACRO_Y_MAX 90.0

	param set MPC_THR_HOVER 70

	param set NAV_ACC_RAD 2

	param set PWM_DISARMED 900
	param set PWM_MIN 1090
	param set PWM_MAX 1910
	param set PWM_MAIN_MIN3 1275
	param set PWM_MAIN_MIN4 1400
	param set PWM_MAIN_MIN5 1430
	param set PWM_MAIN_MIN6 1400

	param set PWM_MAIN_MAX3 1635
	param set PWM_MAIN_MAX4 1760
	param set PWM_MAIN_MAX5 1790
	param set PWM_MAIN_MAX6 1760
	param set PWM_RATE 333

	param set RTL_RETURN_ALT 2.5
	param set RTL_DESCEND_ALT 2.5

	param set CBRK_USB_CHK 197848
	param set BAT1_N_CELLS 4
	param set BAT1_V_CHARGED 4.2

	# TELEM1 ttyS1
	param set MAV_0_CONFIG 101
	param set MAV_0_MODE 0
	param set MAV_0_FORWARD 1
	param set SER_TEL1_BAUD 921600

	param set SDLOG_PROFILE  17

	#param set IMU_GYRO_RATEMAX 400

	param set MC_PWM_HOVER 1706
	param set MPC_THR_HOVER 0.7
fi

set MAV_TYPE 3

set MIXER sductedfan

# use PWM parameters for throttle channel
set PWM_OUT 1


