#!/bin/sh
#
# @name Ducted Fan 4 (CUAV V5 Nano)
#
# @type Ducted Fan
# @class DuctedFan
#
# @output Motor1 Main rotor (M1 / PWM AUX1)
# @output Servo1 Control surface 1 (M5 / PWM AUX5)
# @output Servo2 Control surface 2 (M6 / PWM AUX6)
# @output Servo3 Control surface 3 (M7 / PWM AUX7)
# @output Servo4 Control surface 4 (M8 / PWM AUX8)
#
# @maintainer Meng Chaoheng <chaohengmeng@163.com>
#

. ${R}etc/init.d/rc.mc_defaults

# Use the same two-matrix physical control-effectiveness model as the 22002
# Gazebo Classic airframe: matrix 0 allocates rotor force and matrix 1 allocates
# control-surface torque.
param set-default CA_AIRFRAME 16

param set-default MC_ROLL_P 6
param set-default MC_ROLLRATE_P 0.4
param set-default MC_ROLLRATE_I 0.3
param set-default MC_ROLLRATE_D 0.0
param set-default MC_ROLLRATE_FF 0

param set-default MC_PITCH_P 6
param set-default MC_PITCHRATE_P 0.4
param set-default MC_PITCHRATE_I 0.3
param set-default MC_PITCHRATE_D 0.0
param set-default MC_PITCHRATE_FF 0

param set-default MC_YAW_P 5
param set-default MC_YAWRATE_P 0.2
param set-default MC_YAWRATE_I 0.1
param set-default MC_YAWRATE_D 0
param set-default MC_YAWRATE_FF 0

param set-default MC_ATT_ERR_MODE 3
param set-default MC_YAW_WEIGHT 1

param set-default MPC_VEL_MANUAL 6
# param set-default MPC_XY_CRUISE 5
# param set-default MPC_XY_P 0.95
# param set-default MPC_XY_TRAJ_P 0.5
param set-default MPC_XY_VEL_MAX 8
# param set-default MPC_XY_VEL_P_ACC 2

# param set-default MPC_Z_P 1
# param set-default MPC_Z_VEL_I_ACC 2
# param set-default MPC_Z_VEL_MAX_DN 1
# param set-default MPC_Z_VEL_MAX_UP 3
# param set-default MPC_Z_VEL_P_ACC 4

# INDI
param set-default CA_FORCE_CUTOFF 5
param set-default CA_TORQ_CUTOFF 8
param set-default IMU_DGYRO_CUTOFF 10
param set-default IMU_GYRO_CUTOFF 110
param set-default IMU_GYRO_RATEMAX 800
param set-default IMU_GYRO_NF0_FRQ 35

param set-default MPC_MASS 1.56
param set-default MC_J_X 0.01149
param set-default MC_J_Y 0.01153
param set-default MC_J_Z 0.00487

# The 1.56 kg airframe hovered at motor signal x=0.7146 with THR_MDL_FAC=0.
# Preserve that measured signal with the quadratic thrust model:
#   MPC_THR_HOVER = x^2 = 0.510653
#   Fmax = mass*g/MPC_THR_HOVER = 29.9584 N
param set-default MPC_THR_HOVER 0.510653
param set-default THR_MDL_FAC 1
param set-default RTL_RETURN_ALT 2.5
param set-default RTL_DESCEND_ALT 2.5
param set-default NAV_ACC_RAD 2


# Effectiveness unit contract (control_allocation/df4.m):
#   v = [tau; F] = B*u, with tau [N m], F [N]. The physical actuator vector u
#   contains rotor thrust [N] and surface deflection [rad]. Parameters use
#   u = U*u_norm, so PX4 is configured with B*U and allocates
#   v = (B*U)*u_norm. CA_ROTOR0_CT is maximum thrust [N]; each
#   CA_SV_CSx_TRQ_* is the moment at normalized surface command +1 [N m] and
#   already includes the 20 deg maximum deflection.
param set-default CA_ROTOR_COUNT 1
param set-default CA_ROTOR0_AX 0
param set-default CA_ROTOR0_AY 0
param set-default CA_ROTOR0_AZ -1
param set-default CA_ROTOR0_PX 0
param set-default CA_ROTOR0_PY 0
param set-default CA_ROTOR0_PZ 0.05
param set-default CA_ROTOR0_CT 29.9584
param set-default CA_ROTOR0_KM 0

param set-default CA_SV_CS_COUNT 4
param set-default CA_SV_CS0_TRQ_R -0.166227
param set-default CA_SV_CS0_TRQ_P 0
param set-default CA_SV_CS0_TRQ_Y 0.068681
param set-default CA_SV_CS1_TRQ_R 0
param set-default CA_SV_CS1_TRQ_P -0.166227
param set-default CA_SV_CS1_TRQ_Y 0.068681
param set-default CA_SV_CS2_TRQ_R 0.166227
param set-default CA_SV_CS2_TRQ_P 0
param set-default CA_SV_CS2_TRQ_Y 0.068681
param set-default CA_SV_CS3_TRQ_R 0
param set-default CA_SV_CS3_TRQ_P 0.166227
param set-default CA_SV_CS3_TRQ_Y 0.068681



# CUAV V5 Nano has no PX4IO. With the px4_fmu-v5 build its physical M1-M8
# outputs are the FMU outputs exposed by PX4 as PWM AUX. M2-M4 are unused.
param set-default PWM_AUX_FUNC1 101
param set-default PWM_AUX_FUNC5 201
param set-default PWM_AUX_FUNC6 202
param set-default PWM_AUX_FUNC7 203
param set-default PWM_AUX_FUNC8 204

# AUX1-4, AUX5-6 and AUX7-8 are separate FMU timer groups. Use PX4's current
# 400 Hz PWM default for the ESC group. KST X08H V6.0 digital servos are
# specified for 1520 us / 333 Hz operation.
param set-default PWM_AUX_TIM0 400
param set-default PWM_AUX_TIM1 333
param set-default PWM_AUX_TIM2 333

# Effective M1 motor values from the flown 15003 configuration.
param set-default PWM_AUX_DIS1 900
param set-default PWM_AUX_MIN1 1075
param set-default PWM_AUX_MAX1 1950

# Latest flown v1.12.3 per-servo calibration used PWM_MAIN5-8. On the CUAV
# V5 Nano these physical M5-M8 outputs are PWM_AUX5-8. CENTER is the midpoint
# of each legacy MIN/MAX pair, and DIS keeps the surfaces centered while disarmed.
param set-default PWM_AUX_DIS5 1540
param set-default PWM_AUX_MIN5 1360
param set-default PWM_AUX_CENT5 1540
param set-default PWM_AUX_MAX5 1720

param set-default PWM_AUX_DIS6 1430
param set-default PWM_AUX_MIN6 1250
param set-default PWM_AUX_CENT6 1430
param set-default PWM_AUX_MAX6 1610

param set-default PWM_AUX_DIS7 1500
param set-default PWM_AUX_MIN7 1320
param set-default PWM_AUX_CENT7 1500
param set-default PWM_AUX_MAX7 1680

param set-default PWM_AUX_DIS8 1490
param set-default PWM_AUX_MIN8 1310
param set-default PWM_AUX_CENT8 1490
param set-default PWM_AUX_MAX8 1670

param set-default CBRK_USB_CHK 197848

param set-default BAT1_N_CELLS 4
param set-default BAT1_V_CHARGED 4.2

# Companion computer on TELEM1 or sik radio
param set-default MAV_0_CONFIG 101
param set-default SER_TEL1_BAUD 57600 # CUAV 57600, other 921600

# Run one EKF instance. The sensor hub selects one primary IMU and magnetometer.
# Single EKF
param set-default EKF2_MULTI_IMU 0
param set-default EKF2_MULTI_MAG 0
param set-default SENS_IMU_MODE 1
param set-default SENS_MAG_MODE 1

# Enable only GNSS0 + barometer + magnetometer
# param set-default EKF2_SENS_EN 1281

# IMU state estimation
# param set-default EKF2_IMU_CTRL 7

# GNSS: horizontal position + altitude + 3D velocity
# param set-default EKF2_GPS_CTRL 7

# Barometer height aiding
# param set-default EKF2_BARO_CTRL 1

# Automatic magnetometer fusion
# param set-default EKF2_MAG_TYPE 0

# GPS is the primary height reference
# param set-default EKF2_HGT_REF 1

# Explicitly disable unused aiding
# param set-default EKF2_OF_CTRL 0
# param set-default EKF2_EV_CTRL 0
# param set-default EKF2_RNG_CTRL 0
# param set-default EKF2_RNGBC_CTRL 0
# param set-default EKF2_DRAG_CTRL 0

# The CUAV V5 Nano is upright with its heading arrow pointing aft.
param set-default SENS_BOARD_ROT 4 # Yaw 180 deg

# CUAV V5 Nano IMUs and the GNSS antenna are mounted directly above the
# centre of gravity. PX4 body axes are FRD, so 12 cm above is Z = -0.12 m.
# param set-default EKF2_IMU_POS_X 0
# param set-default EKF2_IMU_POS_Y 0
param set-default EKF2_IMU_POS_Z -0.12
# param set-default SENS_GPS0_OFFX 0
# param set-default SENS_GPS0_OFFY 0
param set-default SENS_GPS0_OFFZ -0.13


param set-default SDLOG_PROFILE  1


# For future
# param set-default RPM_CAP_ENABLE 1
# param set-default PWM_AUX_FUNC9 2070   # A1 / Capture 1 = RPM Input
# param set-default RPM_PULS_PER_REV N # motor
