/****************************************************************************
 *
 *   Copyright (c) 2026 PX4 Development Team. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Neither the name PX4 nor the names of its contributors may be
 *    used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 ****************************************************************************/

#pragma once

#include "FlightTaskManualAltitudeSmoothVel.hpp"

#include <lib/motion_planning/HeadingSmoothing.hpp>
#include <lib/motion_planning/PositionSmoothing.hpp>
#include <lib/slew_rate/SlewRate.hpp>
#include <uORB/PublicationMulti.hpp>
#include <uORB/topics/orbit_status.h>

/**
 * Multicopter figure-eight trajectory task.
 *
 * The horizontal reference is a rotated Lissajous curve in the local NED frame:
 *
 *   q(theta) = [A sin(theta), B sin(2 theta)]^T
 *   p(theta) = center + R(psi) q(theta)
 *
 * where A is the major radius, B = A * MC_F8_RAT, psi is the entry heading
 * plus MC_F8_HDG, and theta is advanced according to the requested ground speed.
 * The exact first and second derivatives used for velocity and acceleration
 * feed-forward are documented next to _generateTrackingSetpoints().
 *
 * During the approach, position, velocity, acceleration and jerk references are
 * generated by PositionSmoothing. During tracking, the task publishes finite
 * horizontal position references together with exact velocity and acceleration
 * feed-forward, so path-error feedback is provided by the multicopter position
 * outer loop. Vertical references are provided by
 * FlightTaskManualAltitudeSmoothVel. Yaw and NED-frame yaw-rate references are
 * also published. TrajectorySetpoint jerk is logging-only in the current
 * multicopter position controller, so tracking jerk is intentionally NAN.
 */
class FlightTaskFigureEight : public FlightTaskManualAltitudeSmoothVel
{
public:
	FlightTaskFigureEight();
	~FlightTaskFigureEight() override = default;

	bool activate(const trajectory_setpoint_s &last_setpoint) override;
	bool update() override;
	bool applyCommandParameters(const vehicle_command_s &command, bool &success) override;

private:
	static constexpr float kRadiusMin = 1.f;
	static constexpr float kInitialMajorRadius = 5.f;
	static constexpr float kHorizontalAcceptanceRadius = 0.5f;
	static constexpr int kClosestPointSamples = 72;

	void _adjustParametersByStick();
	void _configurePositionSmoothing();
	void _findClosestPhase();
	void _generateApproachSetpoints();
	void _generateTrackingSetpoints();
	void _generateYawSetpoint(const matrix::Vector2f &tangent_velocity);
	void _resetApproachSmoothing();
	void _setTrajectoryHeadingFromYaw();
	void _sanitizeParameters(float &radius, float &velocity) const;
	bool _isAtApproachPoint() const;
	bool _sendTelemetry();

	matrix::Vector2f _curvePosition(float phase) const;
	matrix::Vector2f _curveFirstDerivative(float phase) const;
	matrix::Vector2f _curveSecondDerivative(float phase) const;
	matrix::Vector2f _rotateToLocalFrame(const matrix::Vector2f &vector) const;

	void _ekfResetHandlerPositionXY(const matrix::Vector2f &delta_xy) override;
	void _ekfResetHandlerPositionZ(float delta_z) override;
	void _ekfResetHandlerHeading(float delta_psi) override;

	matrix::Vector3f _center{};
	float _major_radius{5.f};
	float _minor_radius{2.5f};
	float _minor_ratio{0.5f};
	float _heading_offset{0.f};
	float _trajectory_velocity{1.f};
	float _phase{0.f};
	float _trajectory_heading{0.f};
	float _initial_heading{0.f};
	int _yaw_behaviour{orbit_status_s::ORBIT_YAW_BEHAVIOUR_HOLD_FRONT_TANGENT_TO_CIRCLE};
	bool _started_clockwise{true};

	bool _in_approach{true};
	PositionSmoothing _position_smoothing;
	SlewRate<float> _slew_rate_velocity;
	HeadingSmoothing _heading_smoothing;

	uORB::PublicationMulti<orbit_status_s> _orbit_status_pub{ORB_ID(orbit_status)};

	DEFINE_PARAMETERS(
		(ParamFloat<px4::params::MC_F8_VEL>) _param_mc_f8_vel,
		(ParamFloat<px4::params::MC_F8_RAT>) _param_mc_f8_ratio,
		(ParamFloat<px4::params::MC_F8_HDG>) _param_mc_f8_heading,
		(ParamFloat<px4::params::MC_F8_ACC>) _param_mc_f8_acceleration,
		(ParamFloat<px4::params::MC_ORBIT_RAD_MAX>) _param_mc_orbit_rad_max,
		(ParamInt<px4::params::MC_ORBIT_YAW_MOD>) _param_mc_orbit_yaw_mod,
		(ParamFloat<px4::params::MPC_XY_CRUISE>) _param_mpc_xy_cruise,
		(ParamFloat<px4::params::MPC_YAWRAUTO_MAX>) _param_mpc_yawrauto_max,
		(ParamFloat<px4::params::MPC_YAWRAUTO_ACC>) _param_mpc_yawrauto_acc,
		(ParamFloat<px4::params::MPC_XY_TRAJ_P>) _param_mpc_xy_traj_p,
		(ParamFloat<px4::params::NAV_MC_ALT_RAD>) _param_nav_mc_alt_rad,
		(ParamFloat<px4::params::MPC_XY_ERR_MAX>) _param_mpc_xy_err_max,
		(ParamFloat<px4::params::MPC_ACC_HOR>) _param_mpc_acc_hor,
		(ParamFloat<px4::params::MPC_JERK_AUTO>) _param_mpc_jerk_auto,
		(ParamFloat<px4::params::MPC_ACC_UP_MAX>) _param_mpc_acc_up_max,
		(ParamFloat<px4::params::MPC_ACC_DOWN_MAX>) _param_mpc_acc_down_max,
		(ParamFloat<px4::params::MPC_Z_V_AUTO_UP>) _param_mpc_z_v_auto_up,
		(ParamFloat<px4::params::MPC_Z_V_AUTO_DN>) _param_mpc_z_v_auto_dn,
		(ParamFloat<px4::params::MPC_XY_VEL_MAX>) _param_mpc_xy_vel_max
	)
};
